[package]
name = "shortlinks"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
color-eyre = "0.6"
eyre = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
